"""
Django settings for rainscale project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.getenv('DEBUG', 0)))

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',         # DEFAULT
    'django.contrib.auth',          # DEFAULT
    'django.contrib.contenttypes',  # DEFAULT
    'django.contrib.sessions',      # DEFAULT
    'django.contrib.messages',      # DEFAULT
    'django.contrib.staticfiles',   # DEFAULT
    'user',                         # APP
    'location',                     # APP
    'experiment',                   # APP
    'model',                        # APP
]

# Adiciona a configuração do modelo de usuário personalizado

AUTH_USER_MODEL = 'user.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # DEFAULT
    'whitenoise.middleware.WhiteNoiseMiddleware',  # STATIC
    'django.contrib.sessions.middleware.SessionMiddleware',  # DEFAULT
    'django.middleware.common.CommonMiddleware',  # DEFAULT
    'django.middleware.csrf.CsrfViewMiddleware',  # DEFAULT
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # DEFAULT
    'django.contrib.messages.middleware.MessageMiddleware',  # DEFAULT
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # DEFAULT
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# # PostgreSQL
# DATABASES = {
#     'default': {
#         'ENGINE': os.getenv('DB_ENGINE', 'change-me'),
#         'NAME': os.getenv('POSTGRES_DB', 'change-me'),
#         'USER': os.getenv('POSTGRES_USER', 'change-me'),
#         'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'change-me'),
#         'HOST': os.getenv('POSTGRES_HOST', 'change-me'),
#         'PORT': os.getenv('POSTGRES_PORT', 'change-me'),
#     }
# }

# SQLite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Diretório onde os arquivos estáticos coletados serão armazenados em produção
STATIC_ROOT = BASE_DIR / 'staticfiles'

# URL para acessar arquivos estáticos
STATIC_URL = '/static/'

# Diretórios adicionais de arquivos estáticos (para desenvolvimento)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# GZIP + Cache otimizado
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Midia carregadas para o sistema
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
