# Generated by Django 5.1.1 on 2025-05-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Modelo')),
                ('temporalidade', models.CharField(choices=[('UNK', 'Desconhecido'), ('1hr', '1 hora'), ('1hrCM', '1 hora (climate model)'), ('1hrPt', '1 hora (ponto)'), ('3hr', '3 horas'), ('3hrPt', '3 horas (ponto)'), ('6hr', '6 horas'), ('6hrPt', '6 horas (ponto)'), ('day', 'Diário'), ('dec', 'Década'), ('fx', 'Fixo'), ('mon', 'Mensal'), ('monC', 'Mensal (climatologia)'), ('monPt', 'Mensal (ponto)'), ('month', 'Mensal (alternativo)'), ('subhrPt', 'Sub-horário (ponto)'), ('yr', 'Anual'), ('yrPt', 'Anual (ponto)')], max_length=50, verbose_name='Temporalidade da Variavel')),
                ('variavel', models.CharField(choices=[('UNK', 'Desconhecido'), ('pr', 'Precipitação'), ('pr_acum', 'Precipitação Acumulada')], max_length=50, verbose_name='Variável')),
                ('variavel_unidade', models.CharField(choices=[('UNK', 'Desconhecido'), ('mm', 'mm'), ('kg m-2 s-1', 'kg m-2 s-1')], max_length=50, verbose_name='Unidade da Variável')),
                ('pontos', models.FileField(upload_to='points/', verbose_name='Pontos do Modelo')),
                ('modelo', models.FileField(upload_to='models/', verbose_name='Modelo de Aprendizado de Máquina')),
                ('caderno', models.FileField(blank=True, null=True, upload_to='notebooks/', verbose_name='Caderno de Modelo')),
                ('repositorio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Repositório do Modelo')),
                ('lat_maxima', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Latitude Máxima do Modelo')),
                ('lat_minima', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Latitude Mínima do Modelo')),
                ('lon_maxima', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Longitude Máxima do Modelo')),
                ('lon_minima', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Longitude Mínima do Modelo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
