# Generated by Django 5.1.1 on 2025-05-01 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do País')),
                ('contorno', models.JSONField(blank=True, null=True, verbose_name='Contorno do País (.json)')),
                ('lat_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Latitude Máxima do País')),
                ('lat_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Latitude Mínima do País')),
                ('lon_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Longitude Máxima do País')),
                ('lon_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Longitude Mínima do País')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Região')),
                ('contorno', models.JSONField(blank=True, null=True, verbose_name='Contorno da Região')),
                ('lat_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Latitude Máxima da Região')),
                ('lat_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Latitude Mínima da Região')),
                ('lon_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Longitude Máxima da Região')),
                ('lon_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Longitude Mínima da Região')),
                ('nacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiao', to='location.nation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
