# Generated by Django 5.1.1 on 2025-05-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='contorno',
            field=models.FileField(upload_to='contorno/', verbose_name='Contorno do País (.json)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='contorno',
            field=models.FileField(upload_to='contorno/', verbose_name='Contorno da Região'),
        ),
    ]
