# Generated by Django 5.1.1 on 2025-05-01 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiment', '0001_initial'),
        ('location', '0001_initial'),
        ('model', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model',
            name='dados_locais',
            field=models.ManyToManyField(blank=True, related_name='modelo', to='experiment.localdata'),
        ),
        migrations.AddField(
            model_name='model',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='location.region'),
        ),
        migrations.AddField(
            model_name='model',
            name='simulacoes',
            field=models.ManyToManyField(blank=True, related_name='modelo', to='experiment.simulation'),
        ),
    ]
